##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## compiles program
##

all:
	make -C solver/ all
	make -C generator/ all

clean:
	make -C solver/ clean
	make -C generator/ clean

fclean:
	make -C solver/ fclean
	make -C generator/ fclean

re:
	make -C solver/ re
	make -C generator/ re

.PHONY:		all clean fclean re
